// ============================================================
//  Pakistan Tourism — Central Data Store
// ============================================================

export const destinations = [
  {
    id: "1",
    name: "Hunza Valley",
    slug: "hunza-valley",
    tagline: "Where Earth Meets Heaven",
    description: "Hunza Valley is a mountainous valley in the Gilgit-Baltistan region of Pakistan. It is known for its stunning natural beauty, with snow-capped peaks, crystal-clear rivers, and lush green valleys. The valley is home to ancient forts, traditional villages, and some of the world's highest mountains including Rakaposhi and Ultar Sar.",
    shortDescription: "A breathtaking valley surrounded by towering peaks and ancient culture in Gilgit-Baltistan.",
    image: "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    heroImage: "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    images: [
      "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
      "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
      "/dr-muhammad-amer-TXJEdxs5Hh4-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Gilgit-Baltistan",
    region: "North",
    bestTimeToVisit: "April – October",
    duration: "4–7 Days",
    rating: 4.9,
    reviews: 2847,
    highlights: ["Baltit Fort", "Attabad Lake", "Rakaposhi Viewpoint", "Khunjerab Pass", "Hussaini Bridge"],
    activities: ["Trekking", "Photography", "Cultural Tours", "Jeep Safaris"],
    coordinates: { lat: 36.3167, lng: 74.6500 },
    category: "Mountains",
    featured: true,
    difficulty: "Moderate",
  },
  {
    id: "2",
    name: "Swat Valley",
    slug: "swat-valley",
    tagline: "The Switzerland of Pakistan",
    description: "Swat Valley, called the 'Switzerland of Pakistan', is a lush valley in Khyber Pakhtunkhwa. It features meadows, crystal rivers, and snow-capped peaks. The valley is rich in Buddhist archaeological sites and traditional Pashtun culture.",
    shortDescription: "The Switzerland of Pakistan — lush meadows, rivers, and ancient Buddhist heritage.",
    image: "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    heroImage: "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    images: [
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
      "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
      "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
    ],
    location: "Khyber Pakhtunkhwa",
    region: "North",
    bestTimeToVisit: "May – September",
    duration: "3–5 Days",
    rating: 4.8,
    reviews: 1923,
    highlights: ["Malam Jabba", "Mahodand Lake", "Udegram Buddhist Monastery", "Fizagat Park", "Mingora Bazaar"],
    activities: ["Skiing", "Trekking", "Sightseeing", "Cultural Tours"],
    coordinates: { lat: 35.2200, lng: 72.4200 },
    category: "Valleys",
    featured: true,
    difficulty: "Easy",
  },
  {
    id: "3",
    name: "Skardu",
    slug: "skardu",
    tagline: "Gateway to the Roof of the World",
    description: "Skardu is the capital of Baltistan and serves as the gateway to K2 and other 8000m peaks. The region offers stunning blue lakes, rugged mountains, and ancient Buddhist rock carvings. A paradise for trekkers and adventurers worldwide.",
    shortDescription: "Gateway to K2 with dramatic landscapes, Alpine lakes, and world-class treks.",
    image: "/luke-richardson-dI7vfR1Bqcg-unsplash.jpg",
    heroImage: "/luke-richardson-dI7vfR1Bqcg-unsplash.jpg",
    images: [
      "/luke-richardson-dI7vfR1Bqcg-unsplash.jpg",
      "/paul-crook-vWpXyrKa0lU-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Gilgit-Baltistan",
    region: "North",
    bestTimeToVisit: "May – October",
    duration: "5–10 Days",
    rating: 4.9,
    reviews: 3211,
    highlights: ["Shangrila Resort", "Upper Kachura Lake", "Deosai National Park", "K2 Base Camp", "Shigar Fort"],
    activities: ["Mountaineering", "Trekking", "Camping", "Photography"],
    coordinates: { lat: 35.2975, lng: 75.6333 },
    category: "Mountains",
    featured: true,
    difficulty: "Challenging",
  },
  {
    id: "4",
    name: "Naran & Kaghan",
    slug: "naran-kaghan",
    tagline: "Alpine Paradise in Summer",
    description: "Naran and Kaghan are twin valleys in the Mansehra District, known for their scenic beauty, alpine meadows, and pristine lakes. Famous for their cool climate during summers — a top family destination in Pakistan.",
    shortDescription: "Twin alpine valleys with pristine lakes and cool summer retreats.",
    image: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    heroImage: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    images: [
      "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
      "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Khyber Pakhtunkhwa",
    region: "North",
    bestTimeToVisit: "May – September",
    duration: "3–5 Days",
    rating: 4.7,
    reviews: 2104,
    highlights: ["Saif-ul-Mulook Lake", "Lulusar Lake", "Babusar Pass", "Ansoo Lake", "Shogran Valley"],
    activities: ["Lake Visits", "Camping", "Photography", "Trekking"],
    coordinates: { lat: 34.9100, lng: 73.6500 },
    category: "Valleys",
    featured: false,
    difficulty: "Easy",
  },
  {
    id: "5",
    name: "Fairy Meadows",
    slug: "fairy-meadows",
    tagline: "Magic at the Foot of a Giant",
    description: "Fairy Meadows is a beautiful grassland near the base camp of Nanga Parbat — the 'Killer Mountain'. Accessible by a challenging jeep track, it offers breathtaking close-up views of the world's 9th highest mountain. Camping here is bucket-list worthy.",
    shortDescription: "A magical alpine meadow with staggering views of Nanga Parbat.",
    image: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    heroImage: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    images: [
      "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
      "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Gilgit-Baltistan",
    region: "North",
    bestTimeToVisit: "May – September",
    duration: "2–4 Days",
    rating: 4.8,
    reviews: 1567,
    highlights: ["Nanga Parbat Views", "Camping", "Beyal Camp", "Rakhiot Glacier", "Star Gazing"],
    activities: ["Camping", "Trekking", "Photography", "Stargazing"],
    coordinates: { lat: 35.3833, lng: 74.5833 },
    category: "Mountains",
    featured: true,
    difficulty: "Moderate",
  },
  {
    id: "6",
    name: "Lahore",
    slug: "lahore",
    tagline: "The Mughal Soul of Pakistan",
    description: "Lahore is the cultural capital of Pakistan, known for its Mughal architecture, vibrant bazaars, and rich history. Home to the Badshahi Mosque and Lahore Fort — a UNESCO World Heritage Site — this city pulses with art, food, and history.",
    shortDescription: "Pakistan's cultural capital with stunning Mughal monuments and vibrant bazaars.",
    image: "/zain-raza-BuEBAiZ5DSo-unsplash.jpg",
    heroImage: "/zain-raza-BuEBAiZ5DSo-unsplash.jpg",
    images: [
      "/zain-raza-BuEBAiZ5DSo-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
      "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    ],
    location: "Punjab",
    region: "Central",
    bestTimeToVisit: "October – April",
    duration: "2–4 Days",
    rating: 4.8,
    reviews: 4521,
    highlights: ["Badshahi Mosque", "Lahore Fort", "Shalimar Gardens", "Wagah Border", "Anarkali Bazaar"],
    activities: ["Heritage Tours", "Food Tours", "Shopping", "Cultural Shows"],
    coordinates: { lat: 31.5204, lng: 74.3587 },
    category: "Heritage",
    featured: true,
    difficulty: "Easy",
  },
  {
    id: "7",
    name: "Karachi",
    slug: "karachi",
    tagline: "City of Lights & Arabian Shores",
    description: "Karachi is Pakistan's largest city and economic hub, located on the Arabian Sea coast. A vibrant metropolis known for its beautiful beaches, diverse culture, and delicious food — blending modern urban life with rich heritage.",
    shortDescription: "Pakistan's city of lights — beaches, history, and incredible street food.",
    image: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    heroImage: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    images: [
      "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
      "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Sindh",
    region: "South",
    bestTimeToVisit: "October – April",
    duration: "2–3 Days",
    rating: 4.5,
    reviews: 3890,
    highlights: ["Clifton Beach", "Mohatta Palace", "Quaid-e-Azam Mausoleum", "Port Grand", "Empress Market"],
    activities: ["Beach Activities", "Heritage Tours", "Food Tours", "Shopping"],
    coordinates: { lat: 24.8607, lng: 67.0011 },
    category: "City",
    featured: false,
    difficulty: "Easy",
  },
  {
    id: "8",
    name: "Islamabad",
    slug: "islamabad",
    tagline: "The Capital Nestled in Green Hills",
    description: "Islamabad is Pakistan's modern capital city nestled against the Margalla Hills. Known for its planned architecture, verdant spaces, and serene atmosphere, it blends natural beauty with urban sophistication. Home to the iconic Faisal Mosque.",
    shortDescription: "Pakistan's scenic modern capital — clean, green, and architecturally stunning.",
    image: "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
    heroImage: "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
    images: [
      "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
      "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    ],
    location: "Islamabad Capital Territory",
    region: "Central",
    bestTimeToVisit: "March–May, September–November",
    duration: "1–3 Days",
    rating: 4.6,
    reviews: 2987,
    highlights: ["Faisal Mosque", "Margalla Hills", "Daman-e-Koh", "Pakistan Monument", "Rawal Lake"],
    activities: ["Hiking", "Sightseeing", "Photography", "Museums"],
    coordinates: { lat: 33.6844, lng: 73.0479 },
    category: "City",
    featured: false,
    difficulty: "Easy",
  },
  {
    id: "9",
    name: "Chitral & Kalash",
    slug: "chitral",
    tagline: "Where Ancient Cultures Survive",
    description: "Chitral is a beautiful valley in Khyber Pakhtunkhwa home to the unique Kalash people — an indigenous community with their own distinct culture, language, and vibrant festivals. The valley also hosts Tirich Mir, Pakistan's highest peak.",
    shortDescription: "Home to the ancient Kalash people with unique culture and colorful festivals.",
    image: "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
    heroImage: "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
    images: [
      "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
      "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
      "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
    ],
    location: "Khyber Pakhtunkhwa",
    region: "North",
    bestTimeToVisit: "May – September",
    duration: "3–5 Days",
    rating: 4.9,
    reviews: 1234,
    highlights: ["Kalash Valley", "Tirich Mir", "Chitral Fort", "Shandur Pass", "Chilam Joshi Festival"],
    activities: ["Cultural Tours", "Trekking", "Photography", "Festivals"],
    coordinates: { lat: 35.8517, lng: 71.7864 },
    category: "Culture",
    featured: true,
    difficulty: "Moderate",
  },
  {
    id: "10",
    name: "Gwadar Coast",
    slug: "gwadar",
    tagline: "Where the Desert Meets the Sea",
    description: "Gwadar is a port city on the Arabian Sea coast in Balochistan with pristine beaches and dramatic coastal scenery. Developing as a major economic hub while retaining its raw, unspoiled natural beauty — perfect for beach lovers and those seeking the road less traveled.",
    shortDescription: "Pristine Arabian Sea beaches and dramatic coastal landscapes of Balochistan.",
    image: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    heroImage: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    images: [
      "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
      "/dr-muhammad-amer-TXJEdxs5Hh4-unsplash.jpg",
      "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    ],
    location: "Balochistan",
    region: "South",
    bestTimeToVisit: "October – April",
    duration: "2–4 Days",
    rating: 4.6,
    reviews: 876,
    highlights: ["Gwadar Beach", "Astola Island", "Hammerhead", "Ormara Beach", "Fishing Villages"],
    activities: ["Swimming", "Fishing", "Photography", "Boat Tours"],
    coordinates: { lat: 25.1216, lng: 62.3254 },
    category: "Coastal",
    featured: false,
    difficulty: "Easy",
  },
  {
    id: "11",
    name: "Mohenjo-daro",
    slug: "mohenjo-daro",
    tagline: "5000 Years of Civilisation",
    description: "Mohenjo-daro is an ancient archaeological site of the Indus Valley Civilization, dating back to 2500 BCE. This UNESCO World Heritage Site offers a fascinating glimpse into one of the world's earliest urban civilizations, with well-preserved ruins of a sophisticated ancient city.",
    shortDescription: "UNESCO World Heritage Site — ruins of one of the world's oldest civilizations.",
    image: "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
    heroImage: "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
    images: [
      "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
      "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
      "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    ],
    location: "Sindh",
    region: "South",
    bestTimeToVisit: "October – March",
    duration: "1–2 Days",
    rating: 4.7,
    reviews: 1102,
    highlights: ["Great Bath", "Archaeological Museum", "Granary", "Citadel", "Walking Ruins Tour"],
    activities: ["Archaeological Tours", "Photography", "Museums", "Learning"],
    coordinates: { lat: 27.3230, lng: 68.1389 },
    category: "Heritage",
    featured: false,
    difficulty: "Easy",
  },
  {
    id: "12",
    name: "Shandur Pass",
    slug: "shandur-pass",
    tagline: "World's Highest Polo Ground",
    description: "Shandur Pass is the highest polo ground in the world at 3,700m above sea level. It hosts the famous annual Shandur Polo Festival, connecting Chitral with Gilgit. The area offers breathtaking views of snow-capped peaks and pristine alpine meadows.",
    shortDescription: "Home to the world's highest polo ground and stunning alpine festival.",
    image: "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
    heroImage: "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
    images: [
      "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
      "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
      "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
    ],
    location: "Khyber Pakhtunkhwa",
    region: "North",
    bestTimeToVisit: "June – August",
    duration: "1–2 Days",
    rating: 4.8,
    reviews: 743,
    highlights: ["Polo Festival", "Alpine Meadows", "Mountain Views", "Camping", "Photography"],
    activities: ["Polo Watching", "Camping", "Photography", "Trekking"],
    coordinates: { lat: 36.0167, lng: 72.4833 },
    category: "Adventure",
    featured: false,
    difficulty: "Moderate",
  },
];

export const tourPackages = [
  {
    id: "1",
    name: "Northern Pakistan Adventure",
    slug: "northern-pakistan-adventure",
    description: "Explore the stunning landscapes of Northern Pakistan including Hunza, Skardu, and Fairy Meadows. This comprehensive tour takes you through some of the most beautiful mountain regions on Earth.",
    duration: "10 Days / 9 Nights",
    price: 125000,
    originalPrice: 150000,
    image: "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    destinations: ["Hunza Valley", "Skardu", "Fairy Meadows"],
    includes: ["Luxury Accommodation", "All Meals", "4x4 Transportation", "Expert Guide", "Entrance Fees", "Camping Equipment"],
    highlights: ["Baltit Fort Visit", "Attabad Lake Cruise", "Shangrila Resort Stay", "Fairy Meadows Camping", "Khunjerab Pass"],
    groupSize: "2–12 persons",
    difficulty: "Moderate",
    category: "Adventure",
    rating: 4.9,
    reviews: 312,
    featured: true,
  },
  {
    id: "2",
    name: "Swat Valley Explorer",
    slug: "swat-valley-explorer",
    description: "Discover the beauty of Swat Valley — the Switzerland of Pakistan. Lush green meadows, ancient Buddhist sites, and authentic Pashtun culture await you.",
    duration: "5 Days / 4 Nights",
    price: 65000,
    originalPrice: 75000,
    image: "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    destinations: ["Swat Valley", "Malam Jabba"],
    includes: ["Hotel Accommodation", "Meals", "Private Transport", "Local Guide"],
    highlights: ["Malam Jabba Ski Resort", "Mahodand Lake Visit", "Buddhist Monastery", "Local Bazaar Tour"],
    groupSize: "2–15 persons",
    difficulty: "Easy",
    category: "Cultural",
    rating: 4.7,
    reviews: 198,
    featured: true,
  },
  {
    id: "3",
    name: "K2 Base Camp Trek",
    slug: "k2-base-camp-trek",
    description: "An epic adventure for experienced trekkers. Journey to the base camp of K2 — the world's second highest and most dangerous mountain. An unforgettable life-changing experience.",
    duration: "15 Days / 14 Nights",
    price: 250000,
    originalPrice: 300000,
    image: "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
    destinations: ["Skardu", "Concordia", "K2 Base Camp"],
    includes: ["Camping Equipment", "All Meals", "Experienced Mountain Guide", "Porter Services", "All Permits"],
    highlights: ["K2 Base Camp", "Concordia Junction", "Baltoro Glacier", "Gasherbrum Views", "Ali Camp"],
    groupSize: "2–8 persons",
    difficulty: "Challenging",
    category: "Trekking",
    rating: 5.0,
    reviews: 87,
    featured: true,
  },
  {
    id: "4",
    name: "Cultural Heritage Journey",
    slug: "cultural-heritage-tour",
    description: "Discover Pakistan's rich cultural heritage visiting Lahore, Multan, and ancient Taxila. Mughal architecture, Sufi shrines, and 5000-year-old ruins await you.",
    duration: "7 Days / 6 Nights",
    price: 85000,
    originalPrice: 100000,
    image: "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    destinations: ["Lahore", "Multan", "Taxila"],
    includes: ["5-Star Accommodation", "All Meals", "Private Coach", "Tour Guide", "All Entrance Fees"],
    highlights: ["Badshahi Mosque", "Lahore Fort", "Multan Shrines", "Taxila Archaeological Site", "Wagah Border Show"],
    groupSize: "2–20 persons",
    difficulty: "Easy",
    category: "Heritage",
    rating: 4.8,
    reviews: 445,
    featured: false,
  },
  {
    id: "5",
    name: "Naran Kaghan Family Escape",
    slug: "naran-kaghan-family",
    description: "Perfect family getaway to the beautiful alpine valleys of Naran and Kaghan. Cool weather, scenic glacial lakes, and comfortable accommodations make this the perfect summer retreat.",
    duration: "4 Days / 3 Nights",
    price: 45000,
    originalPrice: 55000,
    image: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    destinations: ["Naran", "Kaghan", "Babusar"],
    includes: ["Family-Friendly Hotels", "All Meals", "Jeep Transport", "Family Guide"],
    highlights: ["Saif-ul-Mulook Lake", "Lulusar Lake", "Shogran Valley", "Babusar Pass Drive"],
    groupSize: "Family of 2–8",
    difficulty: "Easy",
    category: "Family",
    rating: 4.7,
    reviews: 267,
    featured: false,
  },
  {
    id: "6",
    name: "Arabian Coast Adventure",
    slug: "coastal-adventure",
    description: "Explore Pakistan's stunning Arabian Sea coastline from Karachi to Gwadar. Pristine beaches, fishing villages, and dramatic coastal landscapes form this unique road trip experience.",
    duration: "5 Days / 4 Nights",
    price: 75000,
    originalPrice: 90000,
    image: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    destinations: ["Karachi", "Gwadar", "Makran Coast"],
    includes: ["Beach Resorts", "All Meals", "4x4 Transport", "Coastal Guide", "Beach Activities"],
    highlights: ["Clifton Beach", "Gwadar Beach", "Ormara Beach", "Coastal Highway Drive", "Fishing Experience"],
    groupSize: "2–10 persons",
    difficulty: "Easy",
    category: "Coastal",
    rating: 4.6,
    reviews: 134,
    featured: false,
  },
];

export const blogPosts = [
  {
    id: "1",
    title: "10 Most Stunning Destinations in Northern Pakistan You Must Visit",
    slug: "10-stunning-destinations-northern-pakistan",
    excerpt: "From the turquoise lakes of Hunza to the base camp of K2, Northern Pakistan offers experiences that will redefine your understanding of natural beauty.",
    content: `Northern Pakistan is a revelation. With its towering Karakoram and Himalayan peaks, crystal-clear alpine lakes, and ancient cultures, it's one of the most extraordinary regions on our planet...`,
    image: "/blake-verdoorn-cssvEZacHvQ-unsplash.jpg",
    author: "Ahmed Raza",
    authorImage: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    date: "2024-03-15",
    readTime: "8 min read",
    category: "Travel Guide",
    tags: ["Northern Pakistan", "Mountains", "Hunza", "Travel Guide"],
  },
  {
    id: "2",
    title: "Best Time to Visit Hunza Valley: A Month-by-Month Breakdown",
    slug: "best-time-visit-hunza-valley",
    excerpt: "Cherry blossoms in spring, turquoise lakes in summer, golden leaves in autumn — Hunza has a different face every season. Here's exactly when to go.",
    content: `Hunza Valley is one of those rare places that is genuinely beautiful in every season...`,
    image: "/condor-wei-HKUOwPiO4z0-unsplash.jpg",
    author: "Sara Malik",
    authorImage: "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
    date: "2024-02-28",
    readTime: "6 min read",
    category: "Tips",
    tags: ["Hunza", "Best Time", "Seasons", "Planning"],
  },
  {
    id: "3",
    title: "Complete Guide to Trekking in Pakistan: Routes, Permits & Tips",
    slug: "trekking-guide-pakistan",
    excerpt: "Pakistan has more high-altitude treks than almost any country on Earth. This complete guide covers everything from K2 Base Camp to the Crown of the Karakoram.",
    content: `Pakistan is a trekker's paradise. With five of the world's fourteen 8000m peaks within its borders...`,
    image: "/rohit-tandon-9wg5jCEPBsw-unsplash.jpg",
    author: "Omar Farooq",
    authorImage: "/luke-richardson-dI7vfR1Bqcg-unsplash.jpg",
    date: "2024-01-20",
    readTime: "12 min read",
    category: "Adventure",
    tags: ["Trekking", "K2", "Adventure", "Karakoram"],
  },
  {
    id: "4",
    title: "Lahore in 48 Hours: The Ultimate City Guide",
    slug: "lahore-48-hours-guide",
    excerpt: "Lahore is one of South Asia's great cities. With only 48 hours you need a tight itinerary. Here's how to experience the best of the Mughal capital.",
    content: `Lahore never sleeps and never disappoints. The cultural heart of Pakistan...`,
    image: "/fa-creation-XRoH4UMAE9g-unsplash.jpg",
    author: "Ayesha Siddiqui",
    authorImage: "/paul-crook-vWpXyrKa0lU-unsplash.jpg",
    date: "2024-01-10",
    readTime: "7 min read",
    category: "City Guide",
    tags: ["Lahore", "City Guide", "Culture", "Food"],
  },
  {
    id: "5",
    title: "Pakistan's Hidden Gem: The Kalash Valley and Its Unique Culture",
    slug: "kalash-valley-culture-guide",
    excerpt: "The Kalash people of Chitral have maintained their unique traditions for thousands of years. This is your guide to experiencing their extraordinary culture respectfully.",
    content: `The Kalash Valley is unlike anything else in Pakistan — or the world...`,
    image: "/dr-muhammad-amer-TXJEdxs5Hh4-unsplash.jpg",
    author: "Ahmed Raza",
    authorImage: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    date: "2023-12-15",
    readTime: "9 min read",
    category: "Culture",
    tags: ["Kalash", "Culture", "Chitral", "Indigenous"],
  },
  {
    id: "6",
    title: "Pakistan's Coastal Highway: The Ultimate Road Trip Guide",
    slug: "makran-coastal-highway-road-trip",
    excerpt: "The Makran Coastal Highway is one of Asia's most dramatic road trips — 650km of Arabian Sea coastline, desert dunes, and pristine beaches.",
    content: `Few road trips on Earth can match the drama of the Makran Coastal Highway...`,
    image: "/zain-raza-vfJKqrzYwqo-unsplash.jpg",
    author: "Hassan Ali",
    authorImage: "/qasim-nagori-1x3qakkpzZU-unsplash.jpg",
    date: "2023-11-20",
    readTime: "10 min read",
    category: "Road Trip",
    tags: ["Coastal", "Road Trip", "Balochistan", "Gwadar"],
  },
];

export const stats = [
  { value: 18, suffix: "+", label: "Destinations", icon: "MapPin" },
  { value: 50000, suffix: "+", label: "Happy Travelers", icon: "Users" },
  { value: 12, suffix: "+", label: "Tour Packages", icon: "Package" },
  { value: 4.9, suffix: "★", label: "Average Rating", icon: "Star" },
];

export const testimonials = [
  {
    id: 1,
    name: "James Whitfield",
    country: "United Kingdom",
    avatar: "/ffaamunchy-IxhT8pyjveY-unsplash.jpg",
    rating: 5,
    text: "The Hunza Valley trip exceeded every expectation. PakExplorer's guides were world-class and the scenery was unlike anything I've ever seen. Pakistan has jumped to the top of my must-return list.",
    tour: "Northern Pakistan Adventure",
  },
  {
    id: 2,
    name: "Sophia Chen",
    country: "Canada",
    avatar: "/kalen-emsley-Bkci_8qcdvQ-unsplash.jpg",
    rating: 5,
    text: "I was hesitant about Pakistan but this trip changed everything. The landscapes are breathtaking, the people are incredibly warm, and the organization was flawless from start to finish.",
    tour: "K2 Base Camp Trek",
  },
  {
    id: 3,
    name: "Marco Rossi",
    country: "Italy",
    avatar: "/luke-richardson-dI7vfR1Bqcg-unsplash.jpg",
    rating: 5,
    text: "K2 Base Camp was the hardest and most rewarding thing I've ever done. The Baltoro Glacier is simply out of this world. PakExplorer handled everything perfectly.",
    tour: "K2 Base Camp Trek",
  },
  {
    id: 4,
    name: "Aisha Mohammed",
    country: "UAE",
    avatar: "/paul-crook-vWpXyrKa0lU-unsplash.jpg",
    rating: 5,
    text: "Took the family to Naran Kaghan and it was magical. The kids loved Saif-ul-Mulook Lake and we all loved the fresh mountain air. Absolutely will book with PakExplorer again.",
    tour: "Naran Kaghan Family Escape",
  },
];

export const regions = ["All", "North", "Central", "South"];
export const categories = ["All", "Mountains", "Valleys", "Heritage", "City", "Coastal", "Culture", "Adventure"];
